apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/patelraj-41299/cap-2.git
    targetRevision: main
    path: java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
